# Generated by Django 4.2.4 on 2023-11-30 10:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('subscription', '0001_initial'),
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='subcrip_type',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='subscription.subscriptiontype'),
            preserve_default=False,
        ),
    ]
