# Generated by Django 4.2.4 on 2023-12-01 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_customuser_subcrip_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stripe_checkout_session_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
